drop table IF EXISTS users, items, bookings, requests, comments;

create TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)      NOT NULL,
    email    VARCHAR(512)      NOT NULL CONSTRAINT unique_email UNIQUE,
    CONSTRAINT user_const CHECK (name <> '' AND email <> '')
);

create TABLE IF NOT EXISTS requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(10000)    NOT NULL,
    requestor_id BIGINT           NOT NULL REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    created     TIMESTAMP         NOT NULL
);

create TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)      NOT NULL CHECK (name <> ''),
    description VARCHAR(10000)    NOT NULL,
    is_available  boolean         NOT NULL,
    owner_id    BIGINT            REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    request_id  BIGINT            REFERENCES requests (id)
);


create TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date  TIMESTAMP         NOT NULL,
    end_date    TIMESTAMP         NOT NULL,
    item_id     BIGINT            NOT NULL CONSTRAINT bookings_items_fkey REFERENCES items (id) ON update CASCADE,
    booker_id   BIGINT            NOT NULL CONSTRAINT bookings_users_fkey REFERENCES users (id) ON update CASCADE,
    status      VARCHAR(20)       NOT NULL
);


create TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR(1000)  NOT NULL,
    item_id     BIGINT         NOT NULL    CONSTRAINT comments_items_fkey REFERENCES items ON delete CASCADE ON update CASCADE,
    author      VARCHAR(255)   NOT NULL,
    created     TIMESTAMP      NOT NULL
);